name: pr_check

on:
  workflow_dispatch:
  push:
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Restore cache
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/bin
          ~/.cargo/git
          ~/.cargo/registry
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: Install trunk
      uses: jetli/trunk-action@v0.4.0
      with:
        version: 'latest'
    - name: Build
      run: trunk build
      working-directory: examples/overview
    - name: Run tests
      run: cargo test --verbose
      working-directory: examples/overview
